### ISSUE TITLE
Use ups(), downs() and presses() API

### ISSUE THREAD

**Issue by artfuldev** [artfuldev/cycle-keyboard#27]
- [x] Add ups()
- [x] Add downs()
- [x] Add presses()

**Comment by artfuldev** [comment]
If the names of the methods have to be changed, please comment.
I thought, `keyboard.press('shift')` seems more like an imperative call to press a key on the keyboard rather than a stream of keypress events, as compared to `keyboard.presses('shift')`.

Your thoughts, @raquelxmoss  and @Widdershin ?

**Comment by raquelxmoss** [comment]
I think there's subtlety in phrasing there -- in my driver, I suggest that people call it `Keys`, and call `Keys.presses()`, but of course, people can name it whatever they like in their app.

By using `Keyboard`, we're bringing up the idea of a physical keyboard, and you're right that `Keyboard.press()` sounds like "Press the keyboard".

So, in that case, `Keyboard.presses()` sounds better -- it the phasing is more passive, and I feel like I would expect a stream of keyboard presses from that call.

**Comment by artfuldev** [comment]
I'm trying to make this a driver that we own as the community, as a whole.
We are all owners of this driver :+1: 

I would encourage you to pool all the ideas of improving cycle-keys into this project, and it's my hope that we can one day recommend this project as a successor to cycle-keys, instead of having _n_ number of projects targeting the same feature.

**Comment by artfuldev** [comment]
This is, after all, your project :)

**Comment by Widdershin** [comment]
I like ups(), downs() and presses() as names 😄 👍

**Comment by artfuldev** [comment]
Taking this up in https://github.com/cyclejs-community/cycle-keyboard/tree/use-ups-downs-presses-api
