### ISSUE TITLE
Use keycodes library?

### ISSUE THREAD

**Issue by artfuldev** [artfuldev/cycle-keyboard#28]
I'm using a self-built array, sourced from http://keycode.info/
The cycle-keys driver uses a keycode library.

Which do you feel is better, and more comprehensive?

Please comment.

**Comment by artfuldev** [comment]
Once we arrive at the conclusion we can take it up as a task and complete it.

**Comment by raquelxmoss** [comment]
I think [Keycode](https://www.npmjs.com/package/keycode) is more comprehensive. For example, your array has `ctrl` but it is not aliased to `ctl`. That's not a huge problem, though! It can be easily added. There's a small element of maintenance involved there, but I don't think it's onerous.

There is an advantage in using your array, as that's one less dependency. 

I am fine with either implementation, as long as it gets the job done.

**Comment by artfuldev** [comment]
The array I've used is more verbose, which might affect people wanting to quickly use it. I would rather use the referenced library [keycode](https://www.npmjs.com/package/keycode) instead.

But I find that keyCode 8 is mapped to 'backspace' in the referenced library, whereas the key is labelled as 'delete' on a Mac keyboard. Are things like this a concern for users of the keycodes library?

If that is well maintained, I think we can use that instead of having to maintain our own. Or maybe we want to see how the community reacts to bugs like this, if they really face them, before deciding.

**Comment by Widdershin** [comment]
I vote for using `keycode`, I've used it in a few projects with no issues so far.

**Comment by artfuldev** [comment]
Sure, we'll go ahead with adding a peer dependency then...

**Comment by artfuldev** [comment]
Will pick this up in #29
